-- MySQL Script generated by MySQL Workbench
-- Sat Aug 15 19:05:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema esquema_peluches
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esquema_peluches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esquema_peluches` DEFAULT CHARACTER SET utf8mb3 ;
USE `esquema_peluches` ;

-- -----------------------------------------------------
-- Table `esquema_peluches`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_peluches`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `esquema_peluches`.`peluches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquema_peluches`.`peluches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `visitas` INT NULL,
  `usuario_id` INT NOT NULL,
  `adoptador_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `adoptador_id` (`adoptador_id` ASC) VISIBLE,
  CONSTRAINT `peluches_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `esquema_peluches`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `peluches_ibfk_2`
    FOREIGN KEY (`adoptador_id`)
    REFERENCES `esquema_peluches`.`usuarios` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
